version: "3.7"

services:
  # Backend API
  server:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    command: npm start
    working_dir: /usr/src/server
    ports:
      - "3000:3000"
    # Using volumes overrides dockerignore..
    volumes:
      - ./:/usr/src/server
      - /usr/src/server/node_modules
    environment:
      DB_URI: mongodb://mongodb/auth

  # MongoDB
  mongodb:
    build:
      context: .
      dockerfile: ./docker/mongoDB/Dockerfile
    ports:
      - "27017:27017"

  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    ports:
      - "5432:5432"
    #Extract to file
    environment:
      POSTGRES_DB: "auth"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secret"
