version: "3.7"

services:
  # Backend API
  server:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    working_dir: /usr/src/server
    ports:
      - "3000:3000"
    depends_on:
      - "postgres"
    command: npm start
    restart: always
    # Using volumes overrides dockerignore..
    volumes:
      - ./:/usr/src/server
      - /usr/src/server/node_modules
    environment:
      DB_URI: postgres://postgres:secret@postgres:5432/auth

  postgres:
    container_name: db
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    ports:
      - "5432:5432"
    restart: always
    #Extract to file
    environment:
      POSTGRES_DB: "auth"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secret"
